import os
import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional, List

# ── Configuration ─────────────────────────────────────────────────────

SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
FROM_EMAIL = os.environ.get("FROM_EMAIL", SMTP_USER)
DEFAULT_TO_EMAIL = os.environ.get("DEFAULT_TO_EMAIL", "")

EMAIL_ENABLED = all([SMTP_HOST, SMTP_USER, SMTP_PASSWORD])


# ── Templates ─────────────────────────────────────────────────────────

INTERVIEW_SUMMARY_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
  .header { background: #0B0C10; padding: 30px; text-align: center; }
  .header h1 { color: #E85D4A; margin: 0; font-size: 22px; }
  .header p { color: #8D99AE; margin: 8px 0 0; font-size: 14px; }
  .body { padding: 30px; }
  .score-box { background: #1A1D23; color: #ffffff; padding: 24px; border-radius: 10px; text-align: center; margin: 20px 0; }
  .score-value { font-size: 48px; font-weight: bold; color: #E85D4A; }
  .score-label { font-size: 14px; color: #8D99AE; margin-top: 8px; }
  .recommendation { display: inline-block; padding: 10px 24px; border-radius: 8px; font-weight: bold; font-size: 14px; margin-top: 16px; }
  .rec-exceptional { background: #2A9D8F33; color: #2A9D8F; }
  .rec-strong { background: #2A9D8F22; color: #2A9D8F; }
  .rec-adequate { background: #E9C46A33; color: #E9C46A; }
  .rec-risky { background: #E85D4A33; color: #E85D4A; }
  .rec-reject { background: #E85D4A22; color: #E85D4A; }
  .section-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  .section-table th { background: #1A1D23; color: #E85D4A; padding: 12px; text-align: left; font-size: 13px; text-transform: uppercase; }
  .section-table td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
  .footer { background: #f5f5f5; padding: 20px; text-align: center; font-size: 12px; color: #888; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>DIGIDEL Hiring Agent</h1>
    <p>Interview Score Summary</p>
  </div>
  <div class="body">
    <p><strong>Candidate:</strong> {candidate_name}</p>
    <p><strong>Role:</strong> {role_title}</p>
    <p><strong>Interviewer:</strong> {interviewer}</p>
    <p><strong>Date:</strong> {date}</p>
    <p><strong>Session ID:</strong> {session_id}</p>

    <div class="score-box">
      <div class="score-value">{overall_score}</div>
      <div class="score-label">Overall Score (out of 100)</div>
      <div class="recommendation {rec_class}">{recommendation}</div>
    </div>

    <h3 style="color: #1D1D2B; margin-top: 30px;">Section Breakdown</h3>
    <table class="section-table">
      <tr>
        <th>Section</th>
        <th>Weight</th>
        <th>Avg Score</th>
        <th>Weighted</th>
      </tr>
      {section_rows}
    </table>

    <h3 style="color: #1D1D2B; margin-top: 30px;">Notes</h3>
    <p style="background: #f5f5f5; padding: 16px; border-radius: 8px; font-size: 14px; color: #333;">
      {final_notes}
    </p>
  </div>
  <div class="footer">
    Generated by DIGIDEL Hiring Agent · <a href="https://digidel-hiring-agent.onrender.com/interview">Open Interview Tool</a>
  </div>
</div>
</body>
</html>
"""

NEW_CANDIDATE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
  .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
  .header { background: #0B0C10; padding: 30px; text-align: center; }
  .header h1 { color: #E85D4A; margin: 0; font-size: 22px; }
  .body { padding: 30px; }
  .badge { display: inline-block; padding: 6px 14px; border-radius: 20px; font-size: 12px; font-weight: bold; }
  .badge-pass { background: #2A9D8F22; color: #2A9D8F; }
  .badge-reject { background: #E85D4A22; color: #E85D4A; }
  .badge-yellow { background: #E9C46A22; color: #E9C46A; }
  .footer { background: #f5f5f5; padding: 20px; text-align: center; font-size: 12px; color: #888; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>New Candidate Submitted</h1>
  </div>
  <div class="body">
    <p><strong>Name:</strong> {name}</p>
    <p><strong>Email:</strong> {email}</p>
    <p><strong>Role:</strong> {role}</p>
    <p><strong>Experience:</strong> {experience} years</p>
    <p><strong>Skills Count:</strong> {skills_count}</p>
    <p style="margin-top: 20px;"><span class="badge badge-{decision_class}">{decision}</span></p>
    <p style="margin-top: 20px;"><a href="https://digidel-hiring-agent.onrender.com/dashboard" style="color: #E85D4A; font-weight: bold;">View Dashboard →</a></p>
  </div>
  <div class="footer">
    DIGIDEL Hiring Agent · Auto-notification
  </div>
</div>
</body>
</html>
"""


# ── Service ───────────────────────────────────────────────────────────

class EmailService:
    """Async email service for sending interview summaries and candidate alerts."""

    def __init__(self):
        self.enabled = EMAIL_ENABLED
        self.host = SMTP_HOST
        self.port = SMTP_PORT
        self.user = SMTP_USER
        self.password = SMTP_PASSWORD
        self.from_email = FROM_EMAIL or SMTP_USER
        self.default_to = DEFAULT_TO_EMAIL

    async def send_email(
        self,
        to: List[str],
        subject: str,
        html_body: str,
        text_body: Optional[str] = None,
    ) -> dict:
        """Send an HTML email via SMTP."""
        if not self.enabled:
            return {"success": False, "error": "Email not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASSWORD"}

        if not to:
            return {"success": False, "error": "No recipients specified"}

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.from_email
        msg["To"] = ", ".join(to)

        if text_body:
            msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        try:
            await aiosmtplib.send(
                msg,
                hostname=self.host,
                port=self.port,
                username=self.user,
                password=self.password,
                start_tls=True,
            )
            return {"success": True, "to": to, "subject": subject}
        except Exception as e:
            return {"success": False, "error": str(e)}

    async def send_interview_summary(
        self,
        session_data: dict,
        to: Optional[List[str]] = None,
    ) -> dict:
        """Send a formatted interview summary email."""
        recipients = to or ([self.default_to] if self.default_to else [])
        if not recipients:
            return {"success": False, "error": "No recipient configured. Set DEFAULT_TO_EMAIL or pass to= parameter."}

        result = session_data.get("calculated_result", {})
        sections = result.get("sections", [])

        # Build section rows
        section_rows = ""
        for s in sections:
            avg = s.get("section_avg", "--")
            weighted = s.get("weighted_score", "--")
            section_rows += f"""
            <tr>
                <td>{s['section_id']}. {s['section_title']}</td>
                <td>{s['weight']}%</td>
                <td>{avg}</td>
                <td>{weighted}</td>
            </tr>
            """

        html = INTERVIEW_SUMMARY_TEMPLATE.format(
            candidate_name=session_data.get("candidate_name", "Unknown"),
            role_title=session_data.get("role_title", "Unknown"),
            interviewer=session_data.get("interviewer", "Unknown"),
            date=session_data.get("completed_at", datetime.now().isoformat()),
            session_id=session_data.get("session_id", ""),
            overall_score=result.get("overall_score", "--"),
            recommendation=result.get("recommendation", "N/A"),
            rec_class=result.get("recommendation_class", ""),
            section_rows=section_rows,
            final_notes=session_data.get("final_notes", "No notes provided.") or "No notes provided.",
        )

        return await self.send_email(
            to=recipients,
            subject=f"Interview Summary: {session_data.get('candidate_name', 'Candidate')} — {result.get('recommendation', 'N/A')}",
            html_body=html,
        )

    async def send_new_candidate_alert(
        self,
        pipeline_result: dict,
        to: Optional[List[str]] = None,
    ) -> dict:
        """Send alert when a new candidate passes the filter."""
        recipients = to or ([self.default_to] if self.default_to else [])
        if not recipients:
            return {"success": False, "error": "No recipient configured"}

        profile = pipeline_result.get("profile", {})
        filter_data = pipeline_result.get("filter", {})
        decision = filter_data.get("decision", "UNKNOWN")
        decision_class = decision.lower().replace("_", "-")

        html = NEW_CANDIDATE_TEMPLATE.format(
            name=profile.get("name", "Unknown"),
            email=profile.get("email", "N/A"),
            role=filter_data.get("role", "Unknown"),
            experience=profile.get("experience_years", "N/A"),
            skills_count=profile.get("skills_count", 0),
            decision=decision,
            decision_class=decision_class,
        )

        return await self.send_email(
            to=recipients,
            subject=f"New Candidate: {profile.get('name', 'Unknown')} — {decision}",
            html_body=html,
        )


# ── Singleton ─────────────────────────────────────────────────────────

email_service = EmailService()
